// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUOyfrmdxYUvDJ-5BS5lAfIpYVU7BxFj0',
    appId: '1:741953154997:web:8f6ecdb88e446f49def3fc',
    messagingSenderId: '741953154997',
    projectId: 'weather-tracking-7c325',
    authDomain: 'weather-tracking-7c325.firebaseapp.com',
    storageBucket: 'weather-tracking-7c325.appspot.com',
    measurementId: 'G-S4Q5L5TLFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjH1lv1iHu1BnpwsbHAFuAnOYjumV8fTM',
    appId: '1:741953154997:android:cf90413e3b17bef4def3fc',
    messagingSenderId: '741953154997',
    projectId: 'weather-tracking-7c325',
    storageBucket: 'weather-tracking-7c325.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8yP_NaIahoLtXlghs1Wi-V7ZCTbY7MlA',
    appId: '1:741953154997:ios:fe5e9b43525f2a4cdef3fc',
    messagingSenderId: '741953154997',
    projectId: 'weather-tracking-7c325',
    storageBucket: 'weather-tracking-7c325.appspot.com',
    iosBundleId: 'com.example.weatherTrackingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8yP_NaIahoLtXlghs1Wi-V7ZCTbY7MlA',
    appId: '1:741953154997:ios:fe5e9b43525f2a4cdef3fc',
    messagingSenderId: '741953154997',
    projectId: 'weather-tracking-7c325',
    storageBucket: 'weather-tracking-7c325.appspot.com',
    iosBundleId: 'com.example.weatherTrackingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUOyfrmdxYUvDJ-5BS5lAfIpYVU7BxFj0',
    appId: '1:741953154997:web:c7b9f1ec93b27972def3fc',
    messagingSenderId: '741953154997',
    projectId: 'weather-tracking-7c325',
    authDomain: 'weather-tracking-7c325.firebaseapp.com',
    storageBucket: 'weather-tracking-7c325.appspot.com',
    measurementId: 'G-ETPCSEDYVP',
  );
}
